/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class buptsse_zero_MainInterface */

#ifndef _Included_buptsse_zero_MainInterface
#define _Included_buptsse_zero_MainInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     buptsse_zero_MainInterface
 * Method:    openFile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_buptsse_zero_MainInterface_openFile (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
